server:
  port: 8082

spring:
  application:
    name: tuniu-ticket-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tuniu?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 3000ms
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: public

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.tuniu.common.domain
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    com.tuniu.ticket: info
